[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
forge_repository = "4smCAEoycSXSvVsyic8ircQmHmENPCHn17Fma83SYVbf"

[programs.localnet]
forge_repository = "4smCAEoycSXSvVsyic8ircQmHmENPCHn17Fma83SYVbf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
